from enum import Enum


class ErrorCode(str, Enum):
    COUPON_IS_ALREADY_EXISTS = 'COUPON_IS_ALREADY_EXISTS'
    COUPON_WITH_SOME_NAME_EXISTS = 'COUPON_WITH_SOME_NAME_EXISTS'
    COUPON_NOT_FOUND = 'COUPON_NOT_FOUND'
    COUPON_IS_ALREADY_ACTIVE = 'COUPON_IS_ALREADY_ACTIVE'
    COUPON_IS_ALREADY_UNACTIVE = 'COUPON_IS_ALREADY_UNACTIVE'
