from enum import Enum


class ErrorCode(str, Enum):
    COUPON_IS_ALREADY_EXISTS = 'COUPON_IS_ALREADY_EXISTS'
    COUPON_WITH_SOME_NAME_EXISTS = 'COUPON_WITH_SOME_NAME_EXISTS'
    COUPON_NOT_FOUND = 'COUPON_NOT_FOUND'
    COUPON_IS_ALREADY_ACTIVE = 'COUPON_IS_ALREADY_ACTIVE'
    COUPON_IS_ALREADY_UNACTIVE = 'COUPON_IS_ALREADY_UNACTIVE'
    COUPON_IS_UNACTIVE = 'COUPON_IS_UNACTIVE'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    USER_HAVE_COUPON_YET = 'USER_HAVE_COUPON_YET'
    USER_NO_HAVE_COUPON_YET = 'USER_NO_HAVE_COUPON_YET'
