services:
  fast_api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - .:/app
    command: /start
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:4.0.3-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    depends_on:
      - db

  db:
    restart: always
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    env_file:
      - .env

volumes:
  postgres_data:
  rabbitmq-data:
