#!/bin/bash

set -o errexit
set -o nounset

celery -A config.celery.connection.app \
  --broker=amqp://"${RABBITMQ_DEFAULT_USER}":"${RABBITMQ_DEFAULT_PASS}"@"${RMQ_HOST}":"${RMQ_PORT}" \
  worker \
  --loglevel=info
