"""create profile table

Revision ID: be211d094fe0
Revises: 1b1c8bdc29e1
Create Date: 2024-08-24 14:39:30.431535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be211d094fe0"
down_revision: Union[str, None] = "1b1c8bdc29e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("first_name", sa.String(length=40), nullable=True),
        sa.Column("last_name", sa.String(length=60), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column("posts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("posts_post_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    op.drop_column("posts", "post_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_post_id_fkey", "posts", "users", ["post_id"], ["id"])
    op.drop_column("posts", "user_id")
    op.drop_table("profiles")
    # ### end Alembic commands ###
