"""fix order

Revision ID: 7c46249ba3f4
Revises: 238f55ae420e
Create Date: 2024-08-30 02:09:47.866281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c46249ba3f4"
down_revision: Union[str, None] = "238f55ae420e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "promocode", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "promocode", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
