"""add coupon_id in Order

Revision ID: d1e308bfa4ed
Revises: 48503797ebb5
Create Date: 2024-10-20 20:39:15.712113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1e308bfa4ed"
down_revision: Union[str, None] = "48503797ebb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("coupon_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "orders", "coupons", ["coupon_id"], ["id"])
    op.drop_column("orders", "promocode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("promocode", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "coupon_id")
    # ### end Alembic commands ###
