"""add secret key in backet

Revision ID: 48503797ebb5
Revises: d5e180680631
Create Date: 2024-10-19 17:29:31.138682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48503797ebb5"
down_revision: Union[str, None] = "d5e180680631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "baskets", sa.Column("unique_temporary_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("baskets", "unique_temporary_id")
    # ### end Alembic commands ###
