"""change user model

Revision ID: 830b6d2e8009
Revises: 50e8ffabe23d
Create Date: 2024-09-26 18:28:18.835653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "830b6d2e8009"
down_revision: Union[str, None] = "50e8ffabe23d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
