"""fix orders

Revision ID: 25938cbce120
Revises: f0437ffefee5
Create Date: 2024-10-07 20:32:00.081131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25938cbce120"
down_revision: Union[str, None] = "f0437ffefee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_user_id_key", "orders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("orders_user_id_key", "orders", ["user_id"])
    # ### end Alembic commands ###
