"""fix user model

Revision ID: 300c2e19bca1
Revises: be211d094fe0
Create Date: 2024-08-25 23:50:00.202747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "300c2e19bca1"
down_revision: Union[str, None] = "be211d094fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password2", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password2")
    # ### end Alembic commands ###
