"""add session field in basket

Revision ID: 6c429aab2c44
Revises: d1e308bfa4ed
Create Date: 2024-10-30 17:01:37.182350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c429aab2c44"
down_revision: Union[str, None] = "d1e308bfa4ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("baskets", sa.Column("session_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("baskets", "session_id")
    # ### end Alembic commands ###
