"""add relationship between basket and coupon

Revision ID: fb5a0ab49610
Revises: 6c429aab2c44
Create Date: 2024-10-30 22:12:50.812954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb5a0ab49610"
down_revision: Union[str, None] = "6c429aab2c44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
