from enum import Enum


class ErrorCode(str, Enum):
    COUPON_ALREADY_USED = 'COUPON_ALREADY_USED'
    COUPON_NOT_HAVE_USER = 'COUPON_NOT_HAVE_USER'
    ZERO_PRODUCTS_IN_BASKET = 'ZERO_PRODUCTS_IN_BASKET'
    STRIPE_PAYMENT_ERRORS = 'STRIPE_PAYMENT_ERRORS'
