from enum import Enum


class ErrorCode(str, Enum):
    CANT_BE_EMPTY_LIST_PRODUCTS = 'CANT_BE_EMPTY_LIST_PRODUCTS'
    NOT_FOUND_PRODUCTS = 'NOT_FOUND_PRODUCTS'
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND'
